[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_APP_TITLE = "DICEL ERP"
  VITE_APP_VERSION = "1.0.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin" 