service: dicel-erp-backend

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: production
  environment:
    NODE_ENV: production
    DB_HOST: localhost
    DB_PORT: 5434
    DB_USER: postgres
    DB_PASS: 0123
    DB_NAME: dicel_erp_development
    JWT_SECRET: 5009d3bd3d3887a936f98af7952673cc7ffa787e50f2e6fbfdde840e23db717635ad62d7be98b7c0a2ecf249f124e58cd58b1cf2e78b87c88c68a9e2cbbb3068
    CORS_ORIGIN: https://d2iq65q7bkruv1.cloudfront.net
    OPENAI_API_KEY: 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
    MAX_FILE_SIZE: 10485760
    UPLOAD_PATH: ./uploads/documents

functions:
  api:
    handler: server.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors:
            origin: 'https://d2iq65q7bkruv1.cloudfront.net'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 5000
    noPrependStageInUrl: true 